// F2 — export contract ABIs (and deployments, when present) from Foundry artifacts into
// packages/shared so server and web never hand-write ABI fragments.
// Usage: (cd contracts && forge build) && node tools/abi-sync.ts [--check]

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'contracts', 'out');
const target = join(root, 'packages', 'shared', 'src', 'abi.ts');
const check = process.argv.includes('--check');

const CONTRACTS: Record<string, string> = {
  arenaAbi: 'BnbPlayArena.sol/BnbPlayArena.json',
  checkpointOracleAbi: 'CheckpointOracle.sol/CheckpointOracle.json',
  statelessSupraVerifierAbi: 'StatelessSupraVerifier.sol/StatelessSupraVerifier.json',
  signedPriceVerifierAbi: 'SignedPriceVerifier.sol/SignedPriceVerifier.json',
  testUsdAbi: 'TestUSD.sol/TestUSD.json',
  faucetAbi: 'TestUSDFaucet.sol/TestUSDFaucet.json',
};

let src = '// GENERATED by tools/abi-sync.ts from contracts/out — do not edit.\n\n';
for (const [name, file] of Object.entries(CONTRACTS)) {
  const artifact = JSON.parse(readFileSync(join(out, file), 'utf8')) as { abi: unknown[] };
  src += `export const ${name} = ${JSON.stringify(artifact.abi)} as const;\n\n`;
}

const deploymentsDir = join(root, 'contracts', 'deployments');
const deployments: Record<string, unknown> = {};
for (const chainId of ['97']) {
  const f = join(deploymentsDir, `${chainId}.json`);
  if (existsSync(f)) deployments[chainId] = JSON.parse(readFileSync(f, 'utf8'));
}
src += `export const DEPLOYMENTS_JSON: Record<string, unknown> = ${JSON.stringify(deployments)};\n`;

if (check) {
  const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
  if (current !== src) {
    console.error('abi drift: run node tools/abi-sync.ts');
    process.exit(1);
  }
} else {
  writeFileSync(target, src);
  console.log(`wrote ${target}`);
}
